### ISSUE TITLE
Typing "RECORD" adds "END" too soon

### ISSUE THREAD

**Issue by richardkchapman** [GordonSmith/vscode-ecl#13]
Shouldn't be adding the END until I type a space (otherwise RECORDOF is a right pain to type). Also, should not be doing this expansion when inside a comment.

**Comment by GordonSmith** [comment]
@pjmagee thoughts?

**Comment by pjmagee** [comment]
For now it might be better to remove this from the auto closing bracket config and maybe  implementing this as part of a language semantic model. :(

**Comment by pjmagee** [comment]
Unless, we can slip in "RECORDOF" into the config before it and have no auto close bracket. Maybe worth a shot.
