### ISSUE TITLE
Treatment of single quote a little odd

### ISSUE THREAD

**Issue by richardkchapman** [GordonSmith/vscode-ecl#15]
When I type a single quote to start a string, nothing special happens...

When I type a second single quote to end the string, I get an extra quote inserted after the cursor.

I think the behaviour was intended to be the other way round?

**Comment by GordonSmith** [comment]
@richardkchapman I was unable to reproduce, but had already started to tweak some of those configuration files - please reopen if you can reproduce on the next release (0.0.12)
