### ISSUE TITLE
Not Connecting to cluster

### ISSUE THREAD

**Issue by iMikePayne** [GordonSmith/vscode-ecl#22]
Just did a fresh install of VS Code and ECL plugin 0.0.16. Can't connect to cluster with correct username and password. Cluster is http protocol. Verified user/password in ECL Watch.

Locating Client Tools.
Generating archive.
Creating workunit.
Launch failed - Error: <html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><title>ESP - Access Denied</title><script type='text/javascript'>function closeWin() { top.opener=top; top.close(); }</script></head><body onload="javascript:closeWin();"><b>Access Denied -- Valid username and password required!</b></body></html>

Also, in launch.json I'm getting 'Warning'
message: ''env.', 'config.' and 'command.' are deprecated, use 'env:', 'config:' and 'command:' instead.'
at: 'line,col'

**Comment by GordonSmith** [comment]
The following launch config is working for me:
```
        {
            "name": "dataland-hthor-submit",
            "type": "ecl",
            "request": "launch",
            "mode": "submit",
            "workspace": "${workspaceRoot}",
            "program": "${file}",
            "protocol": "http",
            "serverAddress": "x.x.x.x",
            "port": 8010,
            "rejectUnauthorized": false,
            "targetCluster": "hthor_dev",
            "eclccPath": "config.ecl.eclccPath",
            "eclccArgs": [],
            "includeFolders": "${config:ecl.includeFolders}",
            "legacyMode": "${config:ecl.legacyMode}",
            "resultLimit": 100,
            "user": "XXX",
            "password": "YYY"
        },
```

**Comment by iMikePayne** [comment]
Pretty much identical to what I have. Still getting same error when I changed"${config.ecl.eclccPath}" to "config.ecl.eclccPath". OS is Windows 10 if that makes any difference.

**Comment by GordonSmith** [comment]
I just re-tested and was only able to reproduce your issue by entering an invalid userID/password combination (to be expected) - silly question, but I don't suppose you are using an invalid ID/PW or have some chars which need to be escaped in your password?
I will be pushing a new update with the fix for eclccPath and the corresponding readme later today so you can retest with that.

**Comment by iMikePayne** [comment]
The discussion we had via email about older HPCC version (5.6) was the issue and the latest update has fixed the issue. Thanks!
