### ISSUE TITLE
Will this run offline?

### ISSUE THREAD

**Issue by jswilt** [GordonSmith/vscode-ecl#29]
Trying to run in VS Code 1.12, no online access.
Installed successfully, but startup gives errors.  Seems the .js is looking for:
https://marketplace.visualstudio.com/__apis/public/gallery/extensionquery
...which is not found, offline.

Also, it can't find "./src/eclMain", but "./src/eclMain.ts" does exist.  Are these the same?  Can I just rename/copy?

Does startup, of Code or the ECL extension, attempt to update or something else online?

**Comment by GordonSmith** [comment]
I believe it should work offline fine.

The "./src/eclMain" specifier is correct and should resolve to the "ts" file - I don't know why this isn't working.

Are you trying to build locally?
