### ISSUE TITLE
ECLReference.chm usage?

### ISSUE THREAD

**Issue by pjmagee** [GordonSmith/vscode-ecl#3]
Would it better for the F1 search to somehow access a `ECLReference.chm` on the local machine if it exists and then maybe a fall back would be to do the web based search?

I had a quick check but I'm not too sure how those call the CHM file appropriately like how it 's done in the ECL IDE. 

I suppose it's quite possible people might just uninstall the ECL IDE but keep the compiler?

**Comment by GordonSmith** [comment]
FYI The compiler is part of the "Client Tools" which is always a separate install package - but the IDE bundles a copy with it (so you can have several versions of the client tools installed and the IDE picks the best match for the server your targeting.

I suspect the chm file doable, but would be a windows only solution...

**Comment by pjmagee** [comment]
I believe there are third party solutions to reading the chm files on linux/mac. Not sure how pretty or supported they are. The chm are pretty nice and seems better in comparison to the search results on hpcc website.

Infact....is there a way to get the source of the chm html files and create a new repository using https://readthedocs.org? I'm not too clued in on what can and cannot be done as I'm not part of HPCC 😛

**Comment by GordonSmith** [comment]
@pjmagee The documentation sources can be found here:  https://github.com/hpcc-systems/HPCC-Documentation I don't know how its organised but I do know of two folks who do.

**Comment by GordonSmith** [comment]
@pjmagee I did actually have this implemented with shift+f1 (highlighted word) and shift+f12 (all docs) to open the inline ECL html pages.  The PR is to update to the new urls since the portal refresh
