### ISSUE TITLE
ecl.eclccPath not honored

### ISSUE THREAD

**Issue by dcamper** [GordonSmith/vscode-ecl#30]
![vscode-eclcc-path-bug](https://user-images.githubusercontent.com/1508532/27918272-0cb518d8-6234-11e7-9b3f-41d2aa5c4fc1.jpeg)

Explicit setting of the eclcc path does not override the eclcc binary found by the ECL plugin; see enclosed.  The path cited in the preference file maps to a 6.4.0 community_6.4.0-rc5 client tools set.

**Comment by dcamper** [comment]
It should be noted that /opt/HPCCSystems/current (in my explicit path) is a symlink.  That may affect how the cited path is evaluated for correctness.

**Comment by GordonSmith** [comment]
Can you confirm if it works when you point it to the linked path?

**Comment by dcamper** [comment]
What do you mean by "linked path?"  I tried it with both the one in the screenshot as well as the actual path, with identical results.

**Comment by GordonSmith** [comment]
You may be missing the corresponding launch passthrough:
```
"eclccPath": "${config:ecl.eclccPath}",
```
See the example in the readme here:  https://marketplace.visualstudio.com/items?itemName=GordonSmith.ecl

**Comment by dcamper** [comment]
That was it.  I had that entry, but its value was ${config.ecl.eclccPath} instead.  In fact, all config-oriented values were delimited with a period instead of a colon.  I've changed them everywhere, and now the correct compiler is found.

Thanks!

**Comment by GordonSmith** [comment]
That was a vscode change at some point.
