### ISSUE TITLE
"Syntax Check All" option. So all files are syntax checked.

### ISSUE THREAD

**Issue by pjmagee** [GordonSmith/vscode-ecl#4]
This can be helpful when potentially doing a small refactor in a code base but are unaware of all places where this might also need updating. Having a global syntax check which iterates all `.ecl` files in the workspace would be super helpful.

At the moment we have a powershell file which does this and spits out any errors by having a Run Powershell debug config in our VS Code. Ideally we would just want to use something like F8 which would do the entire syntax check for all files.

**Comment by GordonSmith** [comment]
This is something that eclipse does in the background automatically and we had some logic to prevent it re-checking ECL files which has already been pulled in as part of a previous syntax check.

I would go with ctrl+shift+b?

**Comment by pjmagee** [comment]
Yeah ctrl+shift+b would be the best option. I'd imagine many using that short cut in the standard Visual Studio for Builds so it would suit well.

**Comment by GordonSmith** [comment]
Will need https://github.com/GordonSmith/vscode-ecl/issues/41 to be fixed first.

**Comment by GordonSmith** [comment]
I have gone with shift+f7 (FYI f7 on its own syntax checks the current file).
