### ISSUE TITLE
STD Library basic top level intellisense suggestions possible?

### ISSUE THREAD

**Issue by pjmagee** [GordonSmith/vscode-ecl#5]
I was thinking something like you type `STD.` and vscode can provide a root top level list of all STD library Export Modules?

Only thing is, the intellisense would have to work outisde of the vscode workspace and pull it the STD Library location e.g `C:\Program Files (x86)\HPCCSystems\6.2.0\clienttools\share\ecllibrary\std`

**Comment by GordonSmith** [comment]
It should be getting pulled in already (assuming a file is using it) - plus it has javadoc meta information which I think vs-code should be auto pulling already, but we are not taking advantage of yet.

**Comment by pjmagee** [comment]
Oh, so the current intellisense should already be pulling back things for `STD.*` like `File` and then showing `STD.File.WaitDfuWorkunit` as an option?

**Comment by pjmagee** [comment]
So if im right, intellisense is only offered if the file is from the current workspace. I looked through some of the code and found that it does a syntax check and at that point there is a nice -M feature to pull back some meta data from the ECL file and load this into the cached metaWorkspace. However something isnt working as intended then. When I type `Std.*` nothing comes up, nor if I try to do something like `Std.Str.*` then the only intellisense that comes back is just VS Code giving suggestions about some keywords used in the current file.

Do the ecl include folders need to manually have the Std/Plugins folder included or am I missing something. Shouldn't need to traverse those directories using node and then manually call syntax check on all the ecl files in the client tools I hope.

**Comment by GordonSmith** [comment]
Currently you will only get intellisense for a "dependent" of an attribute that happens to have been syntax checked.  In theory this should include the any STD libraries that are included.

But what you really want is intellisense for all the known sources + the entire STD library + any bundles/plugins (so if your starting from a blank canvas you will have _some_ meta information at least). 

Also it may be the case that we are not parsing the meta information correctly for STD libraries as the meta information can be a bit inconsistent.
