### ISSUE TITLE
Version 0.23: Error whenever a file is opened or closed

### ISSUE THREAD

**Issue by dcamper** [GordonSmith/vscode-ecl#60]
An XML-formatted error appears, floating, whenever an existing file is opened or closed.  The gist of it is "ESP - Access Denied" and "Valid username and password required".

This is during a session where the referenced HPCC cluster requires no authentication, if that makes a difference.

**Comment by GordonSmith** [comment]
Do you have a launch config pointing at a server you don't have access to?  If so, either delete it, or change its type from ecl to eclx or similar.

**Comment by GordonSmith** [comment]
@dcamper do you happen to have a screen shot?

**Comment by dcamper** [comment]
![screenshot](https://user-images.githubusercontent.com/1508532/33448260-26ed1d44-d5cb-11e7-8887-34e3c463e2cd.jpeg)

Can't get a picture of the tooltip.  The error seems to pop up intermittently as well.

**Comment by GordonSmith** [comment]
@dcamper double check your launch config you may have one in there with no credentials (but I could be on the wrong track)

**Comment by dcamper** [comment]
I definitely have some with no credentials; credentials are not required to access clusters without authentication enabled.  Are you saying that I have to put something in for every cluster, regardless?

**Comment by GordonSmith** [comment]
Nope - I am guessing that you have a launch config that doesn't work - previously you wouldn't have seen an error until you submitted a job, but now I am pinging them all on file open/startup (to locate all WUs related to that file).

**Comment by GordonSmith** [comment]
If that is the case I need to workout which configs to ignore.  Your case is not too bad as the response comes back very quickly, but if you had a bad IP or a server is down we might have to wait for the timeout before an WUs are displayed (need to think about that).
I can silence the error easily enough, but delaying displaying all the WUs because one server is down would be bad...

**Comment by dcamper** [comment]
So it definitely is related to the launch config, but I can't quite work out which configuration is going wrong.

This particular config contains references to four clusters (with engine variations for each).  One of the clusters is offline at the moment, so it is causing a long delay in reporting an error, like you said.  FYI, it comes back with a "Error:ETIMEDOUT" message.

The others are puzzling.  They actually work; I've verified the credentials with a browser and ECL Watch.  But if I include them in the config, I get the original error.  Only if I reduce the launch config to only the cluster I'm currently talking to, do I manage to prevent the original error from popping up.

**Comment by GordonSmith** [comment]
Ok now you have confirmed the issue I will issue a patch which will popup 1 warning with the config in question and then ignore it from that point on.

Sounds like I may need to recheck I am send the correct 
credentials also...

Or I might add a "monitor" flag to the config for the short term...

**Comment by GordonSmith** [comment]
Ok I have rolled back to 0.0.22 (v0.0.24) while I investigate further.
