### ISSUE TITLE
Old errors not being cleared when file is closed

### ISSUE THREAD

**Issue by dcamper** [GordonSmith/vscode-ecl#61]
Possibly related to GH-41:  If syntax check for a file fails -- errors appear -- then the file is closed without fixing anything, the errors never go away from the Problems pane.

**Comment by GordonSmith** [comment]
That is by design.  Now the is the option to syntax check _all_ files (shift+F7) its not uncommon to have errors shown for files which are not open.

There is a button to clear the error contents manually.

**Comment by dcamper** [comment]
Where is this mysterious button?

**Comment by GordonSmith** [comment]
Hmmm I was looking at the one on the debug console.  Not sure what a nice balance might be...  will need to think about it,

**Comment by GordonSmith** [comment]
Ok I can close the errors for a given window when it closes automatically - plus I can add a ctrl+f7 to clear all.
