### ISSUE TITLE
Will this extension run in the Windows verions of Visual Studio?

### ISSUE THREAD

**Issue by engvold** [GordonSmith/vscode-ecl#72]
Hello Gordon,

I am a consultant working at LexisNexis here in Boca Raton. Saw your extension working in the open source visual studio and it is looking AWESOME... I will be giving it a run in the near future and look forward to seeing how it works for our Roxie Dev stuff!

BTW, my question for you is... will this extension run in the Windows verions of Visual Studio?

Kindly,
Karl Engvold
www.mcint.net

**Comment by GordonSmith** [comment]
Yes (Windows version of VS Code - not regular VS)
