### ISSUE TITLE
Improve defined as ':=' syntax styling

### ISSUE THREAD

**Issue by pjmagee** [GordonSmith/vscode-ecl#9]
So after review and feedback. The standard defined as operator should probably be bold, not italic.

However if the defined as is used inside a function parameter as a named parameter, then the italic styling fits well.

Example to use bold:
```
Export Person := Module // bold

End;
```

```
Std.Date.AdjustDate(param1, day_delta := param2); // This := should be italicised
```

**Comment by GordonSmith** [comment]
FYI I am reverting the current behavior back to plain ":=" (I did have a go at making it italic for the second case but haven't managed to get the correct tmLanguage syntax yet) .
